In [16]:
import pandas as pd
import numpy as np

In [19]:
df=pd.read_csv("cleaned_dataset.csv")
df

,Age,Attrition,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single
0,0,1,0,-1,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
1,1,0,-1,0,-1,0,1,0,-1,0,...,0,0,0,0,0,1,0,0,1,0
2,0,1,1,0,0,1,1,1,-1,-1,...,0,1,0,0,0,0,0,0,0,1
3,0,0,1,0,1,1,0,0,0,-1,...,0,0,0,0,0,1,0,0,1,0
4,-1,0,0,0,-1,-1,1,-1,0,-1,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1351,0,0,0,1,0,0,1,-1,1,0,...,0,1,0,0,0,0,0,0,1,0
1352,0,0,0,0,-1,1,1,-1,-1,1,...,0,0,0,0,0,0,0,0,1,0
1353,-1,0,-1,0,0,0,1,1,1,0,...,0,0,0,1,0,0,0,0,1,0
1354,1,0,0,0,0,1,1,0,-1,0,...,0,0,0,0,0,0,1,0,1,0
1355,0,0,0,0,0,0,1,0,1,0,...,0,1,0,0,0,0,0,0,1,0

In [18]:
df.isnull().sum()

Age                                  0
Attrition                            0
DailyRate                            0
DistanceFromHome                     0
Education                            0
EnvironmentSatisfaction              0
Gender                               0
HourlyRate                           0
JobInvolvement                       0
JobLevel                             0
JobSatisfaction                      0
MonthlyIncome                        0
MonthlyRate                          0
NumCompaniesWorked                   0
OverTime                             0
PercentSalaryHike                    0
PerformanceRating                    0
RelationshipSatisfaction             0
StockOptionLevel                     0
TotalWorkingYears                    0
TrainingTimesLastYear                0
WorkLifeBalance                      0
YearsAtCompany                       0
YearsInCurrentRole                   0
YearsSinceLastPromotion              0
YearsWithCurrManager                 0
BusinessTravel_Travel_Frequently     0
BusinessTravel_Travel_Rarely         0
Department_Research & Development    0
Department_Sales                     0
EducationField_Life Sciences         0
EducationField_Marketing             0
EducationField_Medical               0
EducationField_Other                 0
EducationField_Technical Degree      0
JobRole_Human Resources              0
JobRole_Laboratory Technician        0
JobRole_Manager                      0
JobRole_Manufacturing Director       0
JobRole_Research Director            0
JobRole_Research Scientist           0
JobRole_Sales Executive              0
JobRole_Sales Representative         0
MaritalStatus_Married                0
MaritalStatus_Single                 0
dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1356 entries, 0 to 1355
Data columns (total 45 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1356 non-null   int64
 1   Attrition                          1356 non-null   int64
 2   DailyRate                          1356 non-null   int64
 3   DistanceFromHome                   1356 non-null   int64
 4   Education                          1356 non-null   int64
 5   EnvironmentSatisfaction            1356 non-null   int64
 6   Gender                             1356 non-null   int64
 7   HourlyRate                         1356 non-null   int64
 8   JobInvolvement                     1356 non-null   int64
 9   JobLevel                           1356 non-null   int64
 10  JobSatisfaction                    1356 non-null   int64
 11  MonthlyIncome                      1356 non-null   int64
 12  MonthlyRate                        1356 non-null   int64
 13  NumCompaniesWorked                 1356 non-null   int64
 14  OverTime                           1356 non-null   int64
 15  PercentSalaryHike                  1356 non-null   int64
 16  PerformanceRating                  1356 non-null   int64
 17  RelationshipSatisfaction           1356 non-null   int64
 18  StockOptionLevel                   1356 non-null   int64
 19  TotalWorkingYears                  1356 non-null   int64
 20  TrainingTimesLastYear              1356 non-null   int64
 21  WorkLifeBalance                    1356 non-null   int64
 22  YearsAtCompany                     1356 non-null   int64
 23  YearsInCurrentRole                 1356 non-null   int64
 24  YearsSinceLastPromotion            1356 non-null   int64
 25  YearsWithCurrManager               1356 non-null   int64
 26  BusinessTravel_Travel_Frequently   1356 non-null   int64
 27  BusinessTravel_Travel_Rarely       1356 non-null   int64
 28  Department_Research & Development  1356 non-null   int64
 29  Department_Sales                   1356 non-null   int64
 30  EducationField_Life Sciences       1356 non-null   int64
 31  EducationField_Marketing           1356 non-null   int64
 32  EducationField_Medical             1356 non-null   int64
 33  EducationField_Other               1356 non-null   int64
 34  EducationField_Technical Degree    1356 non-null   int64
 35  JobRole_Human Resources            1356 non-null   int64
 36  JobRole_Laboratory Technician      1356 non-null   int64
 37  JobRole_Manager                    1356 non-null   int64
 38  JobRole_Manufacturing Director     1356 non-null   int64
 39  JobRole_Research Director          1356 non-null   int64
 40  JobRole_Research Scientist         1356 non-null   int64
 41  JobRole_Sales Executive            1356 non-null   int64
 42  JobRole_Sales Representative       1356 non-null   int64
 43  MaritalStatus_Married              1356 non-null   int64
 44  MaritalStatus_Single               1356 non-null   int64
dtypes: int64(45)
memory usage: 476.8 KB

In [21]:
df.describe()

,Age,Attrition,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single
count,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,...,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000,1356.000000
mean,0.062684,0.171091,0.011799,0.110619,0.216814,0.106195,0.598083,-0.005162,-0.270649,-0.149705,...,0.038348,0.191003,0.020649,0.106932,0.029499,0.215339,0.240413,0.061209,0.450590,0.327434
std,0.698798,0.376728,0.649616,0.706014,0.685246,0.694048,0.490466,0.639975,0.715496,0.848097,...,0.192106,0.393236,0.142259,0.309141,0.169262,0.411209,0.427492,0.239803,0.497736,0.469450
min,-2.000000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,-2.000000,-1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,2.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [22]:
X=df.drop('Attrition',axis=1)
y=df['Attrition']

In [23]:
print(X.columns.tolist())

['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager', 'BusinessTravel_Travel_Frequently', 'BusinessTravel_Travel_Rarely', 'Department_Research & Development', 'Department_Sales', 'EducationField_Life Sciences', 'EducationField_Marketing', 'EducationField_Medical', 'EducationField_Other', 'EducationField_Technical Degree', 'JobRole_Human Resources', 'JobRole_Laboratory Technician', 'JobRole_Manager', 'JobRole_Manufacturing Director', 'JobRole_Research Director', 'JobRole_Research Scientist', 'JobRole_Sales Executive', 'JobRole_Sales Representative', 'MaritalStatus_Married', 'MaritalStatus_Single']

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=122)

In [25]:
from sklearn.svm import SVC
dec=SVC(kernel='linear')

In [26]:
dec.fit(X_train,y_train)

SVC(kernel='linear')

In [27]:
y_pred=dec.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [28]:
from sklearn.metrics import accuracy_score
print('Accuracy_score:',round(accuracy_score(y_test,y_pred)*100,2))

Accuracy_score: 88.7

In [30]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[324  11]
 [ 35  37]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.93       335
           1       0.77      0.51      0.62        72

    accuracy                           0.89       407
   macro avg       0.84      0.74      0.78       407
weighted avg       0.88      0.89      0.88       407

In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svc_model = SVC(
    C=1,
    kernel='rbf',
    gamma='scale',
    random_state=42
)

svc_model.fit(X_train_scaled, y_train)

y_pred = svc_model.predict(X_test_scaled)

In [32]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto', 0.01, 0.001]
}

grid_search = GridSearchCV(
    SVC(),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best Cross Validation Accuracy:", grid_search.best_score_)

Best Parameters: {'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}
Best Cross Validation Accuracy: 0.8630186577554999

In [58]:
from sklearn.inspection import permutation_importance
from sklearn.svm import SVC
import pandas as pd

svc = SVC(kernel='rbf')
svc.fit(X_train, y_train)

result = permutation_importance(
    svc,
    X_test,
    y_test,
    n_repeats=10,
    random_state=42
)

feat_imp_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': result.importances_mean
}).sort_values(by='Importance', ascending=False)

print(feat_imp_df)

                              Feature  Importance
13                           OverTime    0.021376
25   BusinessTravel_Travel_Frequently    0.018182
43               MaritalStatus_Single    0.015233
24               YearsWithCurrManager    0.014496
8                            JobLevel    0.014251
9                     JobSatisfaction    0.014251
18                  TotalWorkingYears    0.011057
2                    DistanceFromHome    0.010319
22                 YearsInCurrentRole    0.010074
1                           DailyRate    0.010074
42              MaritalStatus_Married    0.009091
21                     YearsAtCompany    0.007371
0                                 Age    0.006388
4             EnvironmentSatisfaction    0.006143
12                 NumCompaniesWorked    0.005897
35      JobRole_Laboratory Technician    0.005897
15                  PerformanceRating    0.005405
16           RelationshipSatisfaction    0.005160
20                    WorkLifeBalance    0.004668
10                      MonthlyIncome    0.004423
7                      JobInvolvement    0.003931
28                   Department_Sales    0.003931
19              TrainingTimesLastYear    0.003440
11                        MonthlyRate    0.003440
27  Department_Research & Development    0.003440
39         JobRole_Research Scientist    0.003194
6                          HourlyRate    0.002948
3                           Education    0.002948
23            YearsSinceLastPromotion    0.002703
33    EducationField_Technical Degree    0.002457
40            JobRole_Sales Executive    0.002457
5                              Gender    0.002211
41       JobRole_Sales Representative    0.002211
29       EducationField_Life Sciences    0.002211
14                  PercentSalaryHike    0.002211
31             EducationField_Medical    0.001720
17                   StockOptionLevel    0.001720
30           EducationField_Marketing    0.001229
37     JobRole_Manufacturing Director    0.001229
34            JobRole_Human Resources    0.000246
36                    JobRole_Manager    0.000000
38          JobRole_Research Director    0.000000
26       BusinessTravel_Travel_Rarely   -0.000491
32               EducationField_Other   -0.000737

In [ ]:
import joblib

joblib.dump(dec, 'hr_attrition_svc.pkl')
joblib.dump(scaler, 'scaler.pkl')

In [ ]:
model = joblib.load('hr_attrition_svc.pkl')
scaler = joblib.load('scaler.pkl')